import Link from "next/link";
import Head from "next/head";
import Image from "next/image";

export default function Page() {
  return (
    <div>
      <div id="__next">
        <div className="container">
        <Head>
        <title>Samuel Façanha - Meu Site</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <link rel="icon" href="/icons/favicon.ico" />
      </Head>
          <header>
            <h1 className="title">
              Olá, eu sou <br />
              <span className="title">Samuel Façanha</span>
            </h1>
            <p className="description">
              E essa é minha página pessoal feita em Next.js!
            </p>
          </header>

          <img src="/images/perfil.jpg" className="avatar" />
          <div id="GridM">
            <Link href="/projetos">
              <a className="card">
                <h3>Projetos</h3>
                <p>GitHub, GitLab, etc.</p>
              </a>
            </Link>

            <Link href="/contato">
              <a className="card">
                <h3>Contato</h3>
                <p>E-mail, Telegram, etc.</p>
              </a>
            </Link>

            <Link href="/profissional">
              <a className="card">
                <h3>Profissional</h3>
                <p>Currículo e Experiências</p>
              </a>
            </Link>
            {/* <Link href="#">
               <a className="card">
                    <h3>Card4</h3>
                    <p>Text Card4</p>
               </a>
               </Link>
               <Link href="#">
               <a className="card">
                    <h3>Card5</h3>
                    <p>Text Card5</p>
               </a>
               </Link> */}
          </div>
        </div>
      </div>
    </div>
  );
}
